### ISSUE TITLE
CMake Error: No iOS SDK's found in default search path. Manually set CMAKE_IOS_SDK_ROOT or install the iOS SDK.

### ISSUE THREAD

**Issue by zrubenst** [elastos/Elastos.RT#109]
Full error:
```
Generating makefiles...
CMake Error at /home/hostuser/Elastos.RT/Build/CMake/ios.cmake:151 (message):
  No iOS SDK's found in default search path .  Manually set
  CMAKE_IOS_SDK_ROOT or install the iOS SDK.
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
Build finished, elapsed time: 0 Hours, 0 Minutes, 0 Seconds.
```

XCode (Version 9.2) is installed in the correct location and, as per the Build for iOS Readme, ios simulator for iOS 11.1 is installed as well. Docker is setup and running, then `source Setup/SetEnv.sh` selecting option 6 (ios_simulator64) and then `emake` resulting in the error above. All prior setup from the Getting Started readme has been successfully completed as well (with the exception of the Android setup).

Any help is appreciated

**Comment by kevingzhang** [comment]
Hi  @songsjun I am not sure who to assign to. Please take a look and assign to the right person. I looks like the same problem Clarence got yesterday. It could be related to Apple Dev ID.

**Comment by joelliang** [comment]
Hi @zrubenst , can you check your xCode path and switch it if necessary.
https://github.com/elastos/Elastos.RT/blob/master/DevDoc/docs/build_ios.md#check-xcode-path

And, do you have any SDK in this directory?
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
