### ISSUE TITLE
Permission denied, emake command not found

### ISSUE THREAD

**Issue by wenzhenxiang** [elastos/Elastos.RT#201]
hello, I Use dockerized Untuntu_64bit build environment, i want try run a hellocar demo, but it return "permission denied",  so I use sudo passwd root, set root passwd, use root account, and try again, 
emake
-su: emake: command not found

(docker) x86_64.dbg ~/Elastos.RT/Sources/Sample/HelloCar/eco
$ emake
Generating makefiles...
mkdir: cannot create directory ‘/home/hostuser/Elastos.RT/Targets/obj’: Permission denied
bash: cd: /home/hostuser/Elastos.RT/Targets/obj/x86_64.gnu.linux.docker.dbg/mirror: No such file or directory
mkdir: cannot create directory ‘/home/hostuser/Elastos.RT/Targets/obj’: Permission denied
mkdir: cannot create directory ‘/home/hostuser/Elastos.RT/Targets/obj’: Permission denied
mkdir: cannot create directory ‘/home/hostuser/Elastos.RT/Targets/obj’: Permission denied
mkdir: cannot create directory ‘/home/hostuser/Elastos.RT/Targets/obj’: Permission denied
mkdir: cannot create directory ‘/home/hostuser/Elastos.RT/Targets/obj’: Permission denied
bash: cd: /home/hostuser/Elastos.RT/Targets/obj/x86_64.gnu.linux.docker.dbg/mirror/Sample/HelloCar/eco: No such file or directory
Build finished, elapsed time: 0 Hours, 0 Minutes, 0 Seconds.

(docker)root@4d787f649565:/home/hostuser/Elastos.RT/Sources/Sample/HelloCar/eco#
 emake
-su: emake: command not found

**Comment by xuliting** [comment]
in this file ''Elastos.RT/Docs/How_to_run_test_on_ubuntu.md''

1. enter the build environment
    ``` shell
    ~/Elastos.RT$ source Setup/SetEnv.sh linux_64
    ```
2. build Elastos.HelloCar.eco
    ``` shell
    cd ~/Elastos.RT/Sources/Sample/HelloCar/eco
    ~/Elastos.RT/Sources/Sample/HelloCar/eco$ emake
    ```
3. build HelloCar
    ``` shell
    cd ~/Elastos.RT/Sources/Sample/HelloCar
    ~/Elastos.RT/Sources/Sample/HelloCar$ emake
    ```
4. build result
    ``` shell
    ~/Elastos.RT/Sources/Sample/HelloCar$ pd @
    ~/Elastos.RT/Targets/rdk/x86.gnu.linux.dbg/bin$ ll HelloCar
    ```
5. run HelloCar
    ``` shell
    # Run the executable inside the dbg_info directory if you want to debug it with debug symbols
    # We have already "export LD_LIBRARY_PATH=.". So, it will load the *.eco files inside the current directory
    ~/Elastos.RT/Targets/rdk/x86.gnu.linux.dbg/bin$ cd dbg_info
    ~/Elastos.RT/Targets/rdk/x86.gnu.linux.dbg/bin/dbg_info$ ./HelloCar
    ==================================
    =========== Hello Car ============
    ==================================
    Though cat has nine lives, but it can not fly!
    Kitty can not fly!

    FILE: Animal.cpp, LINE: 51, INFO: > Animal::constructor(2, HuaHua)

    HuaHua : wang! wang!
    HuaHua can not fly!

    Though cat has nine lives, but it can not fly!
    CAnimalHelper::CanFly : Kitty can not fly!

    =========== Exit Hello Car ============
    ```

**Comment by wenzhenxiang** [comment]
thanks, the first time I forget run this command .
``` shell
~/Elastos.RT/Sources$ emake 
```
just a suggest, you can add step 3 
``` shell
~/Elastos.RT/Sources$  apt install cmake
```

**Comment by xuliting** [comment]
OK, I'm going to verify this issue and thank you for your participation!

**Comment by xuliting** [comment]
Cmake is already added to this file `Elastos.RT/docker/Dockerfile`. 
After updating the local code, if there are docker related changes, please rebuild a docker image, which will automatically install the required tools. 
If you manually install the missing tool instead of not rebuilding an image; then when you exit docker and enter it again, you will need to manually install it again.
Thank you very much！
