### ISSUE TITLE
emake fails on MacOS Sierra 10.12.6

### ISSUE THREAD

**Issue by waynetogo** [elastos/Elastos.RT#81]
$ emake
Generating makefiles...
-- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yang/Downloads/Elastos.RT/Targets/obj/rdk/arm_64.llvm.ios.dbg/mirror
Scanning dependencies of target build_icu
make[2]: *** No rule to make target `/Users/yang/downloads/elastos.rt/Sources/ThirdParty/icu/source/configure', needed by `ThirdParty/icu/cross-build/lib/libicuuc.a'.  Stop.
make[1]: *** [ThirdParty/CMakeFiles/build_icu.dir/all] Error 2
make: *** [all] Error 2
Build finished, elapsed time: 0 Hours, 0 Minutes, 0 Seconds.

arm_64.dbg ~/downloads/elastos.rt/Sources

**Comment by joelliang** [comment]
I just updated the getting started markdown and fixed some compile issues at #82 .
Please update your code, download the submodules and try again.

**Comment by waynetogo** [comment]
I'm getting this now:


x86_64.dbg ~/downloads/elastos.rt/Sources

$ emake

make[2]: *** No rule to make target `/Users/yang/downloads/elastos.rt/Sources/ThirdParty/icu/source/configure', needed by `ThirdParty/icu/cross-build/lib/libicuuc.a'.  Stop.

make[1]: *** [ThirdParty/CMakeFiles/build_icu.dir/all] Error 2

make: *** [all] Error 2

Build finished, elapsed time: 0 Hours, 0 Minutes, 0 Seconds.


x86_64.dbg ~/downloads/elastos.rt/Sources



________________________________

**Comment by joelliang** [comment]
Have you download the submodules by typing these on command line?
```shell
$ git submodule init
$ git submodule update
```

And also try to `emake clobber` and then `emake` again.

**Comment by waynetogo** [comment]
Yep,


Chiawens-iMac:elastos.rt yang$ source Setup/SetEnv.sh

1) linux     4) host_devtools 7) ios_device

2) arm_android     5) devtools_64 8) linux_32

3) devtools_32     6) ios_simulator64 9) quit

Please enter your choice: 6


x86_64.dbg ~/elastos.rt/Sources

$ emake

make[2]: *** No rule to make target `/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure', needed by `ThirdParty/icu/cross-build/lib/libicuuc.a'.  Stop.

make[1]: *** [ThirdParty/CMakeFiles/build_icu.dir/all] Error 2

make: *** [all] Error 2

Build finished, elapsed time: 0 Hours, 0 Minutes, 0 Seconds.


x86_64.dbg ~/elastos.rt/Sources

$ emake clobber

Clobber...


x86_64.dbg ~/elastos.rt/Sources

$ emake

Generating makefiles...

-- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk

-- The C compiler identification is AppleClang 9.0.0.9000039

-- The CXX compiler identification is AppleClang 9.0.0.9000039

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - failed

-- Detecting C compile features

-- Detecting C compile features - failed

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - failed

-- Detecting CXX compile features

-- Detecting CXX compile features - failed

-- Configuring done

-- Generating done

-- Build files have been written to: /Users/yang/Elastos.RT/Targets/obj/rdk/x86_64.llvm.ios.dbg/mirror

Scanning dependencies of target build_icu

make[2]: *** No rule to make target `/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure', needed by `ThirdParty/icu/cross-build/lib/libicuuc.a'.  Stop.

make[1]: *** [ThirdParty/CMakeFiles/build_icu.dir/all] Error 2

make: *** [all] Error 2

Build finished, elapsed time: 0 Hours, 0 Minutes, 0 Seconds.


x86_64.dbg ~/elastos.rt/Sources



The elastos.rt/Sources/ThirdParty/icu/source/configure file doesn't exist. So I created a blank configure file and got this:


x86_64.dbg ~/elastos.rt/Sources

$ emake

[  1%] Building icu...

Building ICU for host...

/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure: line 1: {rtf1ansiansicpg1252cocoartf1504cocoasubrtf830: command not found

/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure: line 2: {fonttbl}: command not found

/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure: line 3: syntax error near unexpected token `}'

/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure: line 3: `{\colortbl;\red255\green255\blue255;}'

gnumake[3]: *** No targets specified and no makefile found.  Stop.

Building ICU for x86_64...

/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure: line 1: {rtf1ansiansicpg1252cocoartf1504cocoasubrtf830: command not found

/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure: line 2: {fonttbl}: command not found

/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure: line 3: syntax error near unexpected token `}'

/Users/yang/elastos.rt/Sources/ThirdParty/icu/source/configure: line 3: `{\colortbl;\red255\green255\blue255;}'

gnumake[3]: *** No rule to make target `install'.  Stop.

make[2]: *** [ThirdParty/icu/cross-build/lib/libicuuc.a] Error 2

make[1]: *** [ThirdParty/CMakeFiles/build_icu.dir/all] Error 2

make: *** [all] Error 2

Build finished, elapsed time: 0 Hours, 0 Minutes, 0 Seconds.


x86_64.dbg ~/elastos.rt/Sources


Too tired right now after putting baby down for sleep to dig through the code to find out what's missing in the configure file... The configure file probably didn't copy correctly from your end to github.



________________________________

**Comment by joelliang** [comment]
The icu project just removed the tag/commit which we depends on. :(
https://github.com/unicode-org/icu
I'll try to find a mirror repo or use the svn repo later.
